---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5120'] # 5mb
      - id: debug-statements
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--format, parsable, -d, relaxed]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.2"
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
